---
- name: installs httpd mysqld php and calls script to setup and configure wordpress
  hosts: web
  tasks:
   - name: apache setup
     yum: name=httpd
     become: true
     become_user: root
   - name: php setup
     yum: name=php
     become: true
     become_user: root
   - name: php-mysql setup
     yum: name=php
     become: true
     become_user: root
   - name: start apache
     service: name=httpd state=started
     become: true
     become_user: root
   - name: Install mysql
     yum: name=mysql-server
     become: true
     become_user: root
   - name: start mysql
     service: name=mysqld state=started
     become: true
     become_user: root
   - name: copy SQL file to destination
     copy: src=wordpress.sql dest=/home/ec2-user/wordpress.sql
   - name: copy script
     copy: src=setupWP.sh dest=/home/ec2-user/setupWP.sh
   - name: script perms
     shell: chmod +x /home/ec2-user/setupWP.sh
   - name: run script
     shell: /home/ec2-user/setupWP.sh
     become: true
     become_user: root
...
